Lint/UnifiedInteger:
  Exclude:
    - 'migrations/**/*'

Metrics/AbcSize:
  Max: 18

Metrics/BlockLength:
  Max: 45

Metrics/MethodLength:
  Max: 15

Style/ClassVars:
  Exclude:
    - 'db_tools.rb'
    - 'registro.rb'

Style/Documentation:
  Enabled: false
