Lint/UnifiedInteger:
  Exclude:
    - 'migrations/**/*'

Metrics/AbcSize:
  Max: 18

Metrics/BlockLength:
  Exclude:
    - 'migrations/**/*'

Metrics/MethodLength:
  Max: 15

Style/ClassVars:
  Exclude:
    - 'lib/db_tools.rb'
    - 'lib/registro.rb'

Style/Documentation:
  Enabled: false
